Point to v3 of ansible track

diff --git a/tracks/conjur.org/secure-ansible-automation/10-risk-remediated/check-host01 b/tracks/conjur.org/secure-ansible-automation/10-risk-remediated/check-host01
--- a/tracks/conjur.org/secure-ansible-automation/10-risk-remediated/check-host01
+++ b/tracks/conjur.org/secure-ansible-automation/10-risk-remediated/check-host01
@@ -3,10 +3,14 @@ set -euxo pipefail
 
 # check
 echo "Checking the solution of the challenge"
-#if [ ! -f ~/secure-playbook/inventory ]; then
+#if [ ! -f /root/secure-playbook/inventory ]; then
 #  fail-message "Your challenge failed because you did not create an inventory file for Ansible"
 #fi
 
-#if [ ! -f ~/secure-playbook/playbook.yml ]; then
+#if [ ! -f /root/secure-playbook/playbook.yml ]; then
 #  fail-message "Your challenge failed because you did not create an playbook.yml Ansible playbook file"
+#fi
+
+#if ! grep "cat secure-playbook/inventory" ~/.bash_history; then
+#    fail-message "Review the inventory file before continuing"
 #fi
